=== gitpan/XML-Rules/example/Viper_Client.dtd
<!ELEMENT Client (ClientData)*>

<!ELEMENT ClientData (client_desc, branch_desc, branch_ref_no, client_no, address, zip, city, state, country, phone, fax, email_id, contact, notes, division_name, department)>

<!ELEMENT client_desc (#PCDATA)>
<!ELEMENT branch_desc (#PCDATA)>
<!ELEMENT branch_ref_no (#PCDATA)>
<!ELEMENT client_no (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT zip (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT fax (#PCDATA)>
<!ELEMENT email_id (#PCDATA)>
<!ELEMENT contact (#PCDATA)>
<!ELEMENT notes (#PCDATA)>
<!ELEMENT division_name (#PCDATA)>
<!ELEMENT department (#PCDATA)>

=== gitpan/XML-Rules/example/Client.xml
<?xml version="1.0"?>
<!DOCTYPE Client SYSTEM "Viper_Client.dtd">
<Client>
<ClientData>
 <client_desc>YOUNGSTOWN AFB</client_desc>
 <branch_desc>Atlanta - Government</branch_desc>
 <branch_ref_no>48</branch_ref_no>
 <client_no>AFRC200344      </client_no>
 <address>YOUNGSTOWN AFB </address>
 <zip>44473</zip>
 <city>VIENNA</city>
 <state>OH</state>
 <country>USA</country>
 <phone></phone>
 <fax></fax>
 <email_id></email_id>
 <contact></contact>
 <notes></notes>
 <division_name></division_name>
<department></department>
</ClientData>
<ClientData><client_desc>YOUNGSTOWN AFB</client_desc><branch_desc>Atlanta - Government</branch_desc><branch_ref_no>48</branch_ref_no><client_no>AFRC041036      </client_no><address>YOUNGSTOWN AFB </address><zip>44473</zip><city>VIENNA</city><state>OH</state><country>USA</country><phone></phone><fax></fax><email_id></email_id><contact></contact><notes></notes><division_name></division_name><department></department></ClientData><ClientData><client_desc>YUM BRANDS</client_desc><branch_desc>Louisville</branch_desc><branch_ref_no>40</branch_ref_no><client_no>YUMB000001      </client_no><address>16314 ROAN COURT </address><zip>80134</zip><city>PARKER</city><state>CO</state><country>USA</country><phone>303-8053706</phone><fax>303-8059145</fax><email_id></email_id><contact>MARC SCOTT</contact><notes></notes><division_name></division_name><department></department></ClientData><ClientData><client_desc>ZACHRY CONSTRUCTION COMPANY</client_desc><branch_desc>Dallas</branch_desc><branch_ref_no>4</branch_ref_no><client_no>JWDHBZ0003      </client_no><address>P.O. BOX 240130 </address><zip>78224-0130</zip><city>SAN ANTONIO</city><state>TX</state><country>USA</country><phone></phone><fax></fax><email_id></email_id><contact>MANUEL CERTA</contact><notes></notes><division_name></division_name><department></department></ClientData><ClientData><client_desc>ZACHRY CONSTRUCTION CORP</client_desc><branch_desc>Dallas</branch_desc><branch_ref_no>4</branch_ref_no><client_no>JWDHBZ0251      </client_no><address>P.O. BOX 639 </address><zip>77536</zip><city>DEER PARK</city><state>TX</state><country>USA</country><phone></phone><fax></fax><email_id></email_id><contact>RHONDA MUDD</contact><notes></notes><division_name></division_name><department></department></ClientData><ClientData><client_desc>ZACHRY CONSTRUCTION CORPORATION</client_desc><branch_desc>Dallas</branch_desc><branch_ref_no>4</branch_ref_no><client_no>ZACCCP0001      </client_no><address>P.O. BOX 639  </address><zip>77536</zip><city>DEER PARK</city><state>TX</state><country>USA</country><phone>210-4758819</phone><fax></fax><email_id>CANTWELLL@ZACHRY.COM</email_id><contact>LARRY CANTWELL</contact><notes></notes><division_name></division_name><department></department></ClientData><ClientData><client_desc>ZALES</client_desc><branch_desc>Dallas</branch_desc><branch_ref_no>4</branch_ref_no><client_no>ZALES0001       </client_no><address>901 WEST WALNUT HILL LANE </address><zip>75038</zip><city>IRVING</city><state>TX</state><country>USA</country><phone>972-5804988</phone><fax></fax><email_id></email_id><contact>LEESA MCELROY</contact><notes></notes><division_name></division_name><department></department></ClientData><ClientData><client_desc>ZARA CANADA</client_desc><branch_desc>Calgary</branch_desc><branch_ref_no>34</branch_ref_no><client_no>CZARAC1         </client_no><address>1200 McGill College Suite1550</address><zip>H3B 4G7</zip><city>Montreal</city><state>QC</state><country>Canada</country><phone>514-5920469</phone><fax>514-8681522</fax><email_id></email_id><contact>Julie Gadbois</contact><notes></notes><division_name></division_name><department></department></ClientData><ClientData><client_desc>ZARA CANADA</client_desc><branch_desc>Montreal</branch_desc><branch_ref_no>31</branch_ref_no><client_no>MZARA1          </client_no><address>1200 McGill College Suite 1550</address><zip>H3B 4G7</zip><city>Montreal</city><state>QC</state><country>Canada</country><phone>514-8681516</phone><fax>514-8681522</fax><email_id></email_id><contact>Julie Gadbois</contact><notes></notes><division_name></division_name><department></department></ClientData><ClientData><client_desc>ZARA USA INC.</client_desc><branch_desc>FLORIDA</branch_desc><branch_ref_no>38</branch_ref_no><client_no>ZARAUS0001      </client_no><address>645 MADISON AVENUE 6th Floor</address><zip>10022</zip><city>NEW YORK</city><state>NY</state><country>USA</country><phone>212-3551415</phone><fax>212-7451128</fax><email_id></email_id><contact>FABIANNA TASSINI</contact><notes></notes><division_name></division_name><department></department></ClientData><ClientData><client_desc>ZC STERLING CORPORATION</client_desc><branch_desc>Atlanta</branch_desc><branch_ref_no>26</branch_ref_no><client_no>ZCSTER0001      </client_no><address>210 INTERSTATE N. PARKWAY SUITE 400</address><zip>30339</zip><city>ATLANTA</city><state>GA</state><country>USA</country><phone>770-3032725</phone><fax>770-3032799</fax><email_id></email_id><contact>MARLENE KASSENS</contact><notes></notes><division_name></division_name><department></department></ClientData><ClientData><client_desc>ZELLSTOFF CELGAR LIMITED</client_desc><branch_desc>Vancouver</branch_desc><branch_ref_no>35</branch_ref_no><client_no>VCEPUC1         </client_no><address>P.O. BOX 1000  </address><zip>V1N 3H9</zip><city>CASTLEGAR</city><state>BC</state><country>Canada</country><phone>604-8753780</phone><fax>604-8753186</fax><email_id>?</email_id><contact>Lisa Antignani</contact><notes></notes><division_name></division_name><department></department></ClientData><ClientData><client_desc>ZENITH NATIONAL INSURANCE CORP</client_desc><branch_desc>Los Angeles</branch_desc><branch_ref_no>11</branch_ref_no><client_no>ZEN40100        </client_no><address>21255 CALIFIA STREET  </address><zip>91367-5021</zip><city>WOODLAND HILLS</city><state>CA</state><country>USA</country><phone>818-5945021</phone><fax></fax><email_id>
		</email_id><contact>DIANA ADAMSON</contact><notes></notes><division_name></division_name><department></department></ClientData><ClientData><client_desc>ZENITH NATIONAL INSURANCE CORP.</client_desc><branch_desc>Los Angeles</branch_desc><branch_ref_no>11</branch_ref_no><client_no>ZEN40103        </client_no><address>P.O BOX 8002 </address><zip>94588-8602</zip><city>PLEASANTON</city><state>CA</state><country>USA</country><phone>925-4165307</phone><fax></fax><email_id>swalker@zenith. com</email_id><contact>SUE WALKER</contact><notes></notes><division_name></division_name><department></department></ClientData><ClientData><client_desc>ZENITH PRODUCTS CORP.</client_desc><branch_desc>Detroit</branch_desc><branch_ref_no>6</branch_ref_no><client_no>MAS14610        </client_no><address>400 LUKENS DRIVE </address><zip>19720</zip><city>NEW CASTLE </city><state>DE</state><country>USA</country><phone>302-3268240</phone><fax>302-3268402</fax><email_id></email_id><contact>MARIE KEEFER</contact><notes></notes><division_name></division_name><department></department></ClientData><ClientData><client_desc>Zeon Chemicals</client_desc><branch_desc>Louisville</branch_desc><branch_ref_no>40</branch_ref_no><client_no>LHAZON0001      </client_no><address>
